packages:
  - "apps/**/*"
  - "libs/**/*"

overrides:
  postcss: 8.5.18
  sharp: 0.35.4

allowBuilds:
  "@apollo/protobufjs": true
  "@clerk/shared": true
  esbuild: true
  lefthook: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@apollo/protobufjs"
  - "@clerk/shared"
  - esbuild
  - lefthook
  - protobufjs
  - sharp
  - unrs-resolver
