export const RELEASE_GATE_TEST_PATHS = [
  "scripts/tests/alpha-release-smoke.spec.ts",
  "scripts/tests/api-docs-trigger-check.spec.ts",
  "scripts/tests/architecture-policy-check.spec.ts",
  "scripts/tests/bench-threshold-check.spec.ts",
  "scripts/tests/benchmark-workflow.spec.ts",
  "scripts/tests/branch-protection-policy.spec.ts",
  "scripts/tests/changeset-required-check.spec.ts",
  "scripts/tests/ci-executable-policy.spec.ts",
  "scripts/tests/ci-performance-budget.spec.ts",
  "scripts/tests/ci-verification-identity.spec.ts",
  "scripts/tests/ci-workflow.spec.ts",
  "scripts/tests/compiler-baseline-check.spec.ts",
  "scripts/tests/core-coverage-warning-check.spec.ts",
  "scripts/tests/create-croco-app-generated-smoke.spec.ts",
  "scripts/tests/dependency-audit-policy.spec.ts",
  "scripts/tests/doc-examples-check.spec.ts",
  "scripts/tests/first-success-verify.spec.ts",
  "scripts/tests/generated-secret-placeholder-policy.spec.ts",
  "scripts/tests/live-tests-workflow.spec.ts",
  "scripts/tests/normalize-packages.spec.ts",
  "scripts/tests/package-bin-smoke.spec.ts",
  "scripts/tests/package-docs-check.spec.ts",
  "scripts/tests/package-entrypoint-smoke.spec.ts",
  "scripts/tests/package-manifest-contracts.spec.ts",
  "scripts/tests/package-quality-report.spec.ts",
  "scripts/tests/package-roles.spec.ts",
  "scripts/tests/problem-registry.spec.ts",
  "scripts/tests/production-ready-check.spec.ts",
  "scripts/tests/provenance-config-check.spec.ts",
  "scripts/tests/provider-certification-check.spec.ts",
  "scripts/tests/public-api-surface.spec.ts",
  "scripts/tests/release-docs-check.spec.ts",
  "scripts/tests/release-metadata-check.spec.ts",
  "scripts/tests/release-spine-evidence.spec.ts",
  "scripts/tests/release-version-sync.spec.ts",
  "scripts/tests/release-workflow.spec.ts",
  "scripts/tests/repository-policy-audit-workflow.spec.ts",
  "scripts/tests/security-allowlist-metadata-check.spec.ts",
  "scripts/tests/spine-promotion-check.spec.ts",
  "scripts/tests/static-misuse-check.spec.ts",
  "scripts/tests/strict-contract-typecheck.spec.ts",
  "scripts/tests/test-evidence-reconcile.spec.ts",
  "scripts/tests/test-inventory.spec.ts",
  "scripts/tests/test-lane-evidence-check.spec.ts",
  "scripts/tests/test-lane-runner.spec.ts",
  "scripts/tests/tracked-file-mutation-guard.spec.ts",
  "scripts/tests/turbo-cache-contract.spec.ts",
  "scripts/tests/turbo-task-contract.spec.ts",
  "scripts/tests/verification-change-classifier.spec.ts",
  "scripts/tests/verification-command.spec.ts",
  "scripts/tests/verification-manifest.spec.ts",
  "scripts/tests/verification-policy.spec.ts",
  "scripts/tests/verify-circular-allowlist.spec.ts",
] as const;

export const RELEASE_GATE_ENTRYPOINT_PATHS = [
  "scripts/alpha-release-smoke.mts",
  "scripts/api-docs-trigger-check.mts",
  "scripts/architecture-policy-check.mts",
  "scripts/bench-threshold-check.mts",
  "scripts/changeset-required-check.mts",
  "scripts/ci-executable-policy.mts",
  "scripts/ci-performance-budget.mts",
  "scripts/compiler-baseline-check.mts",
  "scripts/core-coverage-warning-check.mts",
  "scripts/create-croco-app-generated-smoke.mts",
  "scripts/decorator-signature-spike.mts",
  "scripts/dependency-audit-policy.mts",
  "scripts/doc-examples-check.mts",
  "scripts/first-success-verify.mts",
  "scripts/generated-secret-placeholder-policy.mts",
  "scripts/normalize-packages.mjs",
  "scripts/package-bin-smoke.mts",
  "scripts/package-docs-check.mts",
  "scripts/package-entrypoint-smoke.mts",
  "scripts/package-quality-report.mts",
  "scripts/packed-decorator-consumers.mts",
  "scripts/problem-registry.mts",
  "scripts/production-ready-check.mts",
  "scripts/provenance-config-check.mts",
  "scripts/provider-certification-check.mts",
  "scripts/public-api-surface.mts",
  "scripts/quick-start-lambda-smoke.mts",
  "scripts/release-docs-check.mts",
  "scripts/release-metadata-check.mts",
  "scripts/release-version-sync.mts",
  "scripts/security-allowlist-metadata-check.mts",
  "scripts/spine-promotion-check.mts",
  "scripts/static-misuse-check.mts",
  "scripts/strict-contract-typecheck.mts",
  "scripts/test-evidence-reconcile.mts",
  "scripts/test-inventory.mts",
  "scripts/test-lane-evidence-check.mts",
  "scripts/test-lane-runner.mts",
  "scripts/tracked-file-mutation-guard.mts",
  "scripts/turbo-cache-contract.mts",
  "scripts/verification-policy.mts",
  "scripts/verify-circular-allowlist.mts",
] as const;

export const RELEASE_GATE_SUPPORT_PATHS = [
  "scripts/branch-protection-policy.json",
  "scripts/branch-protection-policy.mts",
  "scripts/certification-policy.mts",
  "scripts/ci-cacheable-failure-injection.mts",
  "scripts/ci-verification-identity.mts",
  "scripts/core-coverage-config.mts",
  "scripts/create-croco-app-generated-smoke-dependencies.mts",
  "scripts/create-croco-app-generated-smoke-journey-report.mts",
  "scripts/create-croco-app-generated-smoke-matrix.mts",
  "scripts/create-croco-app-generated-smoke-report.mts",
  "scripts/create-croco-app-generated-smoke-support.mts",
  "scripts/first-success-generated-contract.mts",
  "scripts/internal-croco-compatibility-policy.mjs",
  "scripts/package-manifest-contracts.mjs",
  "scripts/package-roles.mts",
  "scripts/peer-dependency-range-policy.mjs",
  "scripts/pnpm-audit-diagnostics.cjs",
  "scripts/pnpm-audit-gzip-recovery.cjs",
  "scripts/release-gate-maintenance.mts",
  "scripts/release-spine-evidence.mts",
  "scripts/release-workflow-only.mjs",
  "scripts/security-gitleaks-smoke.mts",
  "scripts/test-evidence-runtime.mts",
  "scripts/verification-change-classifier.mts",
  "scripts/verification-command.mts",
  "scripts/verification-dispatcher.mts",
  "scripts/verification-manifest.mts",
  "scripts/verification-problem.mts",
  "scripts/version-packages.mts",
  "scripts/workflow-verification-contract.mts",
] as const;

export const RELEASE_GATE_FIXTURE_PATHS = [
  "scripts/fixtures/decorator-signature-spike/diagnostics.snapshot.txt",
  "scripts/fixtures/decorator-signature-spike/diagnostics.ts",
  "scripts/fixtures/decorator-signature-spike/limitations.ts",
  "scripts/fixtures/decorator-signature-spike/negative.ts",
  "scripts/fixtures/decorator-signature-spike/packed-consumer.ts",
  "scripts/fixtures/decorator-signature-spike/positive.ts",
  "scripts/fixtures/decorator-signature-spike/prototype.snapshot.d.ts",
  "scripts/fixtures/decorator-signature-spike/prototype.ts",
  "scripts/fixtures/decorator-signature-spike/tsconfig.declaration.json",
  "scripts/fixtures/decorator-signature-spike/tsconfig.diagnostics.json",
  "scripts/fixtures/decorator-signature-spike/tsconfig.json",
  "scripts/fixtures/packed-decorator-consumers/negative.ts",
  "scripts/fixtures/packed-decorator-consumers/positive.ts",
] as const;

export const RELEASE_GATE_IMPLEMENTATION_PATHS = [
  ...RELEASE_GATE_ENTRYPOINT_PATHS,
  ...RELEASE_GATE_FIXTURE_PATHS,
  ...RELEASE_GATE_SUPPORT_PATHS,
] as const;

export const RELEASE_GATE_WORKFLOW_PATHS = [
  ".github/workflows/benchmark.yml",
  ".github/workflows/ci.yml",
  ".github/workflows/live-tests.yml",
  ".github/workflows/release.yml",
  ".github/workflows/repository-policy-audit.yml",
] as const;

export const RELEASE_GATE_POLICY_INPUT_PATHS = [
  ".changeset/config.json",
  ".github/renovate.json",
  ".gitignore",
  ".gitleaks.toml",
  ".gitleaksignore",
  ".madge-circular-allowlist.txt",
  ".npmrc",
  ".nvmrc",
  ".oxfmtignore",
  ".oxfmtrc.json",
  ".oxlintrc.json",
  ".prettierignore",
  "AGENTS.md",
  "CONTRIBUTING.md",
  "RELEASING.md",
  "benchmarks/baseline.json",
  "benchmarks/thresholds.json",
  "ci-reports/bundle-size/baseline.json",
  "ci-reports/coverage/core-baseline.txt",
  "config/ci-performance-baselines.json",
  "config/live-test-resources.json",
  "croco.arch.json",
  "docs/doc-examples-baseline.json",
  "docs/package-catalog.json",
  "docs/package-docs-baseline.json",
  "docs/problem-code-registry.json",
  "docs/release/croco-1.0-spine.md",
  "docs/release/silent-success-audit.json",
  "package.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "public-api-surface.snapshot.json",
  "scripts/internal-peer-dependency-range-exceptions.json",
  "scripts/security-allowlist-metadata.json",
  "scripts/static-misuse-empty-catch-allowlist.json",
  "scripts/static-misuse-raw-error-allowlist.json",
  "tsconfig.json",
  "tsconfig/contract-strict.baseline.json",
  "turbo.json",
  "vitest.config.bench.ts",
  "vitest.config.ts",
] as const;

export const RELEASE_GATE_MAINTENANCE_PATHS = [
  ...RELEASE_GATE_WORKFLOW_PATHS,
  ...RELEASE_GATE_POLICY_INPUT_PATHS,
  ...RELEASE_GATE_IMPLEMENTATION_PATHS,
  ...RELEASE_GATE_TEST_PATHS,
] as const;

const RELEASE_GATE_MAINTENANCE_PATH_SET = new Set<string>(RELEASE_GATE_MAINTENANCE_PATHS);

export function isReleaseGateMaintenancePath(path: string): boolean {
  return RELEASE_GATE_MAINTENANCE_PATH_SET.has(path);
}
